# This is the version of the Docker Compose file format we are using.
version: '3.7'

# The 'postgres' service uses the 'postgres:latest' image to create a container
# running the latest version of PostgreSQL. It loads environment variables
# from a file named 'variables.env' and maps port 5432 from the container to
# the host machine.
services:
  postgres:
    image: 'postgres:latest'
    env_file:
      - variables.env
    ports:
      - '543
