#version: '3'
#
##networks:
##  mynetwork:
#
#services:
#  app:
#    image: 'spring'
#    build:
#      context: .
#    container_name: marketplace_app
#    depends_on:
#      - db
##    networks:
##      - mynetwork
#    environment:
##      - POSTGRES_USER=admin
##      - POSTGRES_PASSWORD=admin
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/marketplace
#      - SPRING_DATASOURCE_USERNAME=admin
#      - SPRING_DATASOURCE_PASSWORD=admin
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#
#    ports:
#      - 80:80

#  db:
#    image: postgres:12
#    restart: always
#    container_name: postgres
#    environment:
#      - POSTGRES_USER=admin
#      - POSTGRES_PASSWORD=admin
#      - POSTGRES_DB=marketplace
#    ports:
#      - 5432:5432
##    networks:
##      - mynetwork

