version: '3'

services:
  app:
    image: 'spring'
    build:
      context: .
    container_name: marketplace_app
    depends_on:
      - db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/marketplace
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

    ports:
      - 8080:8080

  db:
    image: 'postgres'
    container_name: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=marketplace
    ports:
      - 5432:5432
