version: '3'

services:
  postgres:
    image: 'postgres'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: database_marketplace
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin