version: '3'

services:
  app:
    image: 'spring'
    build:
      context: .
    container_name: marketplace_app
    depends_on:
      - db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/marketplace
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

    ports:
      - 8080:8080

  db:
    image: 'postgres'
    container_name: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=marketplace
    ports:
      - 5432:5432
#services:
#  db:
#    image: 'postgres'
#    container_name: postgres
#    environment:
#      - POSTGRES_USER=admin
#      - POSTGRES_PASSWORD=admin
#
#  app:
#    image: 'spring-project'
#    build:
#      context: .
#    container_name: app
#    depends_on:
#      - db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/database_marketplace
#        - SPRING_DATASOURCE_USERNAME=admin
#        - SPRING_DATASOURCE_PASSWORD=admin
#        - SPRING_JPA_HIBERNATE_DDL_AUTO=update



#  postgres:
#    image: 'postgres'
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_DB: database_marketplace
#      POSTGRES_USER: admin
#      POSTGRES_PASSWORD: admin
#
#  backend:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "80:80"
#    depends_on:
#      - postgres