name: MarketPlace CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Make Gradlew Executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build --exclude-task test --exclude-task pmdMain --exclude-task pmdTest --warning-mode=all

      - name: Finalize Build
        run: echo "Build completed successfully!"

  test:
    needs: build
    runs-on: ubuntu-20.04

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: marketplace
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/marketplace
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin

    steps:
      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432 -U postgres; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 1
          done

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Make Gradlew Executable
        run: chmod +x ./gradlew

      - name: Run Tests with Gradle
        run: ./gradlew test jacocoTestReport

      - name: Finalize Test
        run: echo "Tests completed successfully!"

      - name: Upload Code Coverage
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/html

      - name: Finalize Report of Coverage
        run: echo "Report created!"

  pmd-analysis:
    needs: build
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Make Gradlew Executable
        run: chmod +x ./gradlew

      - name: Run PMD Analysis with Gradle
        run: ./gradlew runPmd

      - name: Upload PMD Report
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: pmd-report
          path: build/reports/pmd

      - name: Finalize PMD Analysis
        run: echo "PMD Analysis completed successfully!"